-- stop table
CREATE TABLE STOP
(
    stop_id   VARCHAR   NOT NULL,
    stop_name VARCHAR NULL,
    created   TIMESTAMP NOT NULL DEFAULT current_timestamp,
    updated   TIMESTAMP NULL,
    PRIMARY KEY (stop_id)
);

-- fare table
CREATE TABLE FARE
(
    fare_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    from_stop_id VARCHAR   NOT NULL,
    to_stop_id   VARCHAR   NOT NULL,
    amount       NUMERIC(20, 2) NULL,
    enabled      BOOLEAN NULL,
    created      TIMESTAMP NOT NULL DEFAULT current_timestamp,
    updated      TIMESTAMP NULL,
    PRIMARY KEY (fare_id)
);

-- foreign keys
ALTER TABLE FARE
    ADD CONSTRAINT from_fare_fk FOREIGN KEY (from_stop_id) REFERENCES STOP (stop_id);
ALTER TABLE FARE
    ADD CONSTRAINT to_fare_fk FOREIGN KEY (to_stop_id) REFERENCES STOP (stop_id);